#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点设置
title: "Guovz"
email: pzhuwjl@qq.com
description: "王继林的个人博客"
keywords: "Guovz"

# 用户信息设置
weibo_username: Guovz
github_username: guovz

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl: "/jekyll-pithy"
url: "http://127.0.0.1:4000"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
# duoshuo_shortname: 

# 百度统计设置
# baidu_analysis:
