permalink: /:year/:month/:day/:title/

# 站点设置
title:
email:
description:
keywords:

# 用户信息设置
weibo_username:
github_username:

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl:
url:


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
# duoshuo_shortname: 

# 百度统计设置
# baidu_analysis:
